import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  Thermometer,
  Zap,
  Layers,
  Bot,
  Settings,
  Play,
  Pause,
  RotateCcw,
  Target,
  Send,
  Blend,
  Clock,
  Rocket,
  MapPin,
  SlidersHorizontal,
  HeartPulse,
  Wind,
  Binary,
  Waves, // Icon for Quantum Drive
  Magnet, // Icon for Magnetic Field
  Sigma, // Icon for Electron Density
  Crosshair, // Icon for Laser
  ShieldCheck, // Icon for Crystal Integrity
  BatteryCharging, // Icon for Energy Level
  Sparkles // Icon for Coherence
} from 'lucide-react';

// --- Interfaces --- 
interface ThermalPoint { x: number; y: number; layer: number; temperature: number; efficiencyFactor: number; powerGenerated: number; }
interface MaterialProperties { name: string; S_eff: number; ZT: number; sigma: number; k: number; color: string; }
interface ChatMessage { sender: 'user' | 'ai'; text: string; }
interface Destination { name: string; distanceLY: number; }
interface ControlCommand { action: string; component: string; value?: any; }
interface ControlPanel { name: string; value: number; min: number; max: number; step: number; unit: string; enabled: boolean; }

// --- NEW Quantum Interfaces ---
interface QuantumDriveParams {
  electronDensityTarget: number; // 0-1: Control over electron flow/plasma density (PDF concept)
  magneticFieldStrength: number; // Tesla: Intensity of the asymmetric magnetic field (PDF concept)
  magneticFieldAsymmetry: number; // 0-1: Degree of asymmetry in the field, crucial for propulsion (PDF concept)
  laserIntensity: number; // 0-1: Intensity of control lasers for state manipulation/coherence (PDF concept)
  electronCoherence: number; // 0-1 (Calculated): State of quantum coherence, affects efficiency/thrust (PDF concept)
  crystalIntegrity: number; // 0-1 (Calculated): Health of the iso-charged crystal structure (PDF concept)
}

interface QuantumPerformance {
  quantumThrust: number; // Newtons: Force generated by electron/field interaction
  quantumDrag: number; // Newtons: Residual quantum/electromagnetic drag, potentially reduced by drive
  quantumPowerConsumption: number; // Watts: Energy needed to maintain fields, lasers, electron control
  quantumHeatGeneration: number; // Watts: Waste heat from inefficiencies
}

type PropulsionMode = 'THERMAL' | 'QUANTUM_ELECTRON';

// --- Materials Data (Thermal Aspect) --- 
const materials: Record<string, MaterialProperties> = {
  bismuth_telluride: { name: 'Telureto de Bismuto (Bi2Te3)', S_eff: 200e-6, ZT: 1.0, sigma: 1.0e5, k: 1.5, color: '#a855f7' },
  selenide_tin: { name: 'Seleneto de Estanho (SnSe)', S_eff: 300e-6, ZT: 1.2, sigma: 0.8e5, k: 1.2, color: '#f97316' },
  skutterudite: { name: 'Skutterudite (CoSb3 based)', S_eff: 250e-6, ZT: 1.4, sigma: 1.2e5, k: 1.8, color: '#22c55e' },
  default_material: { name: 'Material Padrão', S_eff: 100e-6, ZT: 0.8, sigma: 0.5e5, k: 2.0, color: '#888888' }
};
type MaterialKey = keyof typeof materials;

// --- Destinations --- 
const destinations: Record<string, Destination> = {
  none: { name: 'Nenhum (Exploração Livre)', distanceLY: Infinity },
  proxima_centauri: { name: 'Proxima Centauri', distanceLY: 4.25 },
  barnard_star: { name: 'Estrela de Barnard', distanceLY: 5.96 },
  sirius: { name: 'Sirius', distanceLY: 8.61 },
  tau_ceti: { name: 'Tau Ceti', distanceLY: 11.91 },
};
type DestinationKey = keyof typeof destinations;

// --- Constants --- 
const MESH_WIDTH = 500, MESH_HEIGHT = 300, GRID_SIZE = 20, NUM_LAYERS = 5;
const ROWS_PER_LAYER = Math.floor((MESH_HEIGHT / GRID_SIZE) / NUM_LAYERS);
const TOTAL_ROWS = ROWS_PER_LAYER * NUM_LAYERS, COLS = Math.floor(MESH_WIDTH / GRID_SIZE);
const INITIAL_INTERNAL_TEMP = 293.15, TARGET_INTERNAL_TEMP = 301.15;
const HEAT_TRANSFER_COEFFICIENT = 0.05, INTER_LAYER_HEAT_TRANSFER_COEFFICIENT = 0.1;
const TIME_STEP = 0.1, RENDER_INTERVAL_MS = 100;
const API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent";
const API_KEY = "AIzaSyAuFi5KtPsMJI5IC8c5FjvYD5IbuBdwH_U"; // Replace with your actual API key handling

// --- Physics & Travel Constants ---
const SPEED_OF_LIGHT = 299792458;
const SECONDS_PER_YEAR = 31557600;
const METERS_PER_LIGHT_YEAR = SPEED_OF_LIGHT * SECONDS_PER_YEAR;
const MAX_SPEED_FRACTION = 0.0825; // Max speed for THERMAL drive
const MAX_THERMAL_SPEED = MAX_SPEED_FRACTION * SPEED_OF_LIGHT;
const SHIP_MASS = 100000; // kg (Example mass)
const INITIAL_ENERGY_LEVEL = 1e12; // Joules (Example energy)

// --- NEW Quantum Physics Constants (Aligned with PDF Concepts - Requires Calibration) ---
// NOTE: PDF is conceptual. Constants reflect *relationships* described, not exact values.
const K_THRUST = 8e6; // Base thrust scaling. PDF implies strong dependence on controlled electrons and asymmetric fields.
const K_DRAG_BASE = 5e-7; // Base quantum/electromagnetic drag coefficient.
const K_DRAG_REDUCTION_FACTOR = 0.6; // How much coherence/integrity can reduce drag (PDF concept: reduced interaction).
const K_POWER_BASE = 1.5e6; // Base power consumption for quantum drive systems.
const K_POWER_DENSITY = 6e6; // Power scales with electron density control effort.
const K_POWER_FIELD = 2e5; // Power scales significantly with magnetic field strength squared.
const K_POWER_LASER = 3e6; // Power scales with laser control intensity.
const K_HEAT_FACTOR = 0.05; // Reduced base heat factor, inefficiency scales with control intensity.
const QUANTUM_DRIVE_EFFICIENCY_BASE = 0.85; // Assumed base efficiency, modified by coherence/integrity.
const K_COHERENCE_RECOVERY = 0.015; // Rate at which coherence recovers naturally.
const K_COHERENCE_DEGRADE_LASER = 0.06; // Coherence degradation due to laser intensity.
const K_COHERENCE_DEGRADE_FIELD = 0.04; // Coherence degradation due to field strength/asymmetry.
const K_INTEGRITY_DEGRADE_THRUST = 1.5e-9; // Crystal degrades with thrust stress.
const K_INTEGRITY_DEGRADE_HEAT = 2e-8; // Crystal degrades with heat stress.
const MAX_QUANTUM_SPEED = SPEED_OF_LIGHT * 0.99; // Theoretical max for quantum drive.

// --- Temperature Constants ---
const COSMIC_BACKGROUND_TEMP = 3;
const MAX_EXTERNAL_TEMP = 50; // Max temp from velocity (thermal mode)

// --- Sound Effects ---
const playBeep = (frequency: number, duration: number) => {
  if (typeof window !== 'undefined' && (window.AudioContext || (window as any).webkitAudioContext)) {
    const audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
    const oscillator = audioCtx.createOscillator();
    const gainNode = audioCtx.createGain();
    
    oscillator.type = 'sine';
    oscillator.frequency.value = frequency;
    oscillator.connect(gainNode);
    gainNode.connect(audioCtx.destination);
    
    oscillator.start();
    gainNode.gain.exponentialRampToValueAtTime(0.00001, audioCtx.currentTime + duration/1000);
    oscillator.stop(audioCtx.currentTime + duration/1000);
  }
};

const playStatusSound = () => {
  playBeep(800, 100);
  setTimeout(() => playBeep(1000, 100), 150);
};

const playAlertSound = () => {
  playBeep(1200, 200);
  setTimeout(() => playBeep(800, 200), 300);
};

const playQuantumDriveSound = (active: boolean) => {
  if (active) {
    playBeep(440, 150); // Engage sound
  } else {
    playBeep(330, 200); // Disengage sound
  }
};

// --- Fibonacci Sequence Generator ---
function* fibonacciGenerator() {
  let a = 0, b = 1;
  while (true) {
    yield b;
    [a, b] = [b, a + b];
  }
}

// --- Helper Functions --- 
const mixColors = (c1: string, c2: string, r: number): string => {
  try { 
    const v1 = parseInt(c1.slice(1), 16), v2 = parseInt(c2.slice(1), 16); 
    const r1 = (v1 >> 16) & 255, g1 = (v1 >> 8) & 255, b1 = v1 & 255; 
    const r2 = (v2 >> 16) & 255, g2 = (v2 >> 8) & 255, b2 = v2 & 255; 
    const nr = Math.round(r1 * r + r2 * (1 - r)), ng = Math.round(g1 * r + g2 * (1 - r)), nb = Math.round(b1 * r + b2 * (1 - r)); 
    return `#${(1 << 24 | nr << 16 | ng << 8 | nb).toString(16).slice(1).padStart(6, '0')}`; 
  } catch (e) { return '#888888'; } 
};

const getEffectiveMaterialProps = (matKey1: MaterialKey, matKey2: MaterialKey, mixRatio: number): MaterialProperties => {
  if (matKey1 === matKey2) return materials[matKey1];
  const p1 = materials[matKey1], p2 = materials[matKey2];
  return { 
    name: `Mistura (${(mixRatio * 100).toFixed(0)}% ${p1.name} / ${((1 - mixRatio) * 100).toFixed(0)}% ${p2.name})`, 
    S_eff: p1.S_eff * mixRatio + p2.S_eff * (1 - mixRatio), 
    ZT: p1.ZT * mixRatio + p2.ZT * (1 - mixRatio), 
    sigma: p1.sigma * mixRatio + p2.sigma * (1 - mixRatio), 
    k: p1.k * mixRatio + p2.k * (1 - mixRatio), 
    color: mixColors(p1.color, p2.color, mixRatio) 
  };
};

const formatTime = (s: number): string => { 
  const years = Math.floor(s / SECONDS_PER_YEAR);
  const remainingSeconds = s % SECONDS_PER_YEAR;
  const h = Math.floor(remainingSeconds / 3600), m = Math.floor((remainingSeconds % 3600) / 60), sec = Math.floor(remainingSeconds % 60); 
  return `${years > 0 ? `${years}a ` : ''}${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${sec.toString().padStart(2, '0')}`; 
};

const ThermalMeshPage: React.FC = () => {
  // --- State --- 
  const [meshState, setMeshState] = useState<ThermalPoint[][]>([]);
  const [externalTemp, setExternalTemp] = useState(COSMIC_BACKGROUND_TEMP);
  const [materialMixRatio, setMaterialMixRatio] = useState(0.5);
  const [isRunning, setIsRunning] = useState(false);
  const [totalPowerGenerated, setTotalPowerGenerated] = useState(0);
  const [averageInnerTemp, setAverageInnerTemp] = useState(INITIAL_INTERNAL_TEMP);
  const [simulationTime, setSimulationTime] = useState(0);
  const [distanceTraveled, setDistanceTraveled] = useState(0);
  const [currentVelocity, setCurrentVelocity] = useState(0);
  const [fibonacciIndex, setFibonacciIndex] = useState(0);
  const [currentFibValue, setCurrentFibValue] = useState(1);
  const [selectedDestination, setSelectedDestination] = useState<DestinationKey>('none');
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isAiThinking, setIsAiThinking] = useState(false);
  const [autoAdjustEnabled, setAutoAdjustEnabled] = useState(true);
  const [lastStatusReport, setLastStatusReport] = useState(0);
  
  // Controles do sistema
  const [systemComponents, setSystemComponents] = useState({
    propulsion: true,
    thermalControl: true,
    powerGeneration: true,
    navigation: true,
    lifeSupport: true,
    quantumDrive: true
  });

  // Painéis de controle (Thermal/Conventional)
  const [controlPanels, setControlPanels] = useState<Record<string, ControlPanel>>({
    propulsionPower: {
      name: "Propulsão Térmica",
      value: 0.75,
      min: 0,
      max: 1,
      step: 0.01,
      unit: "%",
      enabled: true
    },
    thermalControlPower: {
      name: "Controle Térmico",
      value: 0.8,
      min: 0,
      max: 1,
      step: 0.01,
      unit: "%",
      enabled: true
    },
    powerGenerationEfficiency: {
      name: "Geração Energia",
      value: 0.9,
      min: 0.5,
      max: 1,
      step: 0.01,
      unit: "%",
      enabled: true
    },
    lifeSupportPower: {
      name: "Suporte Vital",
      value: 0.7,
      min: 0,
      max: 1,
      step: 0.01,
      unit: "%",
      enabled: true
    }
  });

  // --- NEW Quantum State ---
  const [propulsionMode, setPropulsionMode] = useState<PropulsionMode>('THERMAL');
  const [quantumDriveParams, setQuantumDriveParams] = useState<QuantumDriveParams>({
    electronDensityTarget: 0.5,
    magneticFieldStrength: 2.0,
    magneticFieldAsymmetry: 0.1,
    laserIntensity: 0.1,
    electronCoherence: 0.9,
    crystalIntegrity: 1.0
  });
  const [quantumPerformance, setQuantumPerformance] = useState<QuantumPerformance>({
    quantumThrust: 0,
    quantumDrag: 0,
    quantumPowerConsumption: 0,
    quantumHeatGeneration: 0
  });
  const [energySourceLevel, setEnergySourceLevel] = useState(INITIAL_ENERGY_LEVEL);

  const simulationIntervalRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const fibGenRef = useRef(fibonacciGenerator());
  const speechSynthesisRef = useRef<SpeechSynthesisUtterance | null>(null);

  // Use fixed materials for now as selection handlers were removed
  const effectiveMaterial = getEffectiveMaterialProps('bismuth_telluride', 'selenide_tin', materialMixRatio);
  const targetDistanceMeters = destinations[selectedDestination].distanceLY * METERS_PER_LIGHT_YEAR;
  const calculateDistanceRemainingLY = useCallback(() => {
      return selectedDestination !== 'none' ? Math.max(0, destinations[selectedDestination].distanceLY - (distanceTraveled / METERS_PER_LIGHT_YEAR)) : Infinity;
  }, [selectedDestination, distanceTraveled]);

  // --- Text-to-Speech Function ---
  const speak = (text: string) => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = 'pt-BR';
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      speechSynthesisRef.current = utterance;
      window.speechSynthesis.speak(utterance);
    }
  };

  // --- Update Control Function (Thermal/Conventional) ---
  const updateControl = (controlName: string, newValue: number | boolean) => {
    setControlPanels(prev => {
      const updatedPanels = { ...prev };
      if (typeof newValue === 'boolean') {
        updatedPanels[controlName] = { ...updatedPanels[controlName], enabled: newValue };
      } else {
         updatedPanels[controlName] = { ...updatedPanels[controlName], value: newValue };
      }
      return updatedPanels;
    });
    playBeep(800, 50);
  };

  // --- NEW Update Quantum Control Function ---
  const updateQuantumControl = (paramName: keyof QuantumDriveParams, newValue: number) => {
    setQuantumDriveParams(prev => {
      let maxVal = 1;
      if (paramName === 'magneticFieldStrength') maxVal = 10; // Example max Tesla
      else if (paramName === 'electronCoherence' || paramName === 'crystalIntegrity') maxVal = 1; // These shouldn't exceed 1
      
      const clampedValue = Math.max(0, Math.min(maxVal, newValue));
      return {
        ...prev,
        [paramName]: clampedValue
      };
    });
    playBeep(900, 40); // Different beep for quantum controls
  };

  // --- Initialization --- 
  const initializeMesh = useCallback(() => {
    const initialMesh: ThermalPoint[][] = Array.from({ length: TOTAL_ROWS }, (_, i) => 
      Array.from({ length: COLS }, (_, j) => ({
        x: j * GRID_SIZE, y: i * GRID_SIZE, layer: Math.floor(i / ROWS_PER_LAYER),
        temperature: INITIAL_INTERNAL_TEMP, efficiencyFactor: 0, powerGenerated: 0
      }))
    );
    setMeshState(initialMesh); 
    setTotalPowerGenerated(0); 
    setAverageInnerTemp(INITIAL_INTERNAL_TEMP);
    setSimulationTime(0); 
    setDistanceTraveled(0); 
    setCurrentVelocity(0);
    setExternalTemp(COSMIC_BACKGROUND_TEMP);
    setFibonacciIndex(0); 
    setCurrentFibValue(1);
    setLastStatusReport(0);
    fibGenRef.current = fibonacciGenerator();
    setChatMessages([]);
    // Reset quantum state
    setPropulsionMode('THERMAL');
    setQuantumDriveParams({
        electronDensityTarget: 0.5,
        magneticFieldStrength: 2.0,
        magneticFieldAsymmetry: 0.1,
        laserIntensity: 0.1,
        electronCoherence: 0.9,
        crystalIntegrity: 1.0
    });
    setQuantumPerformance({
        quantumThrust: 0,
        quantumDrag: 0,
        quantumPowerConsumption: 0,
        quantumHeatGeneration: 0
    });
    setEnergySourceLevel(INITIAL_ENERGY_LEVEL);
  }, []);

  // --- Control Functions for AI ---
  const executeControlCommand = useCallback((command: ControlCommand) => {
    let success = false;
    let message = '';
    
    try {
      const component = command.component.toLowerCase();
      const action = command.action.toLowerCase();
      const value = command.value;

      switch (component) {
        // System toggles
        case 'propulsion':
        case 'thermalcontrol':
        case 'powergeneration':
        case 'navigation':
        case 'lifesupport':
        case 'quantumdrive':
        case 'autoadjust':
          if (action === 'toggle') {
            const systemKey = component as keyof typeof systemComponents | 'autoAdjust';
            if (systemKey === 'autoAdjust') {
                setAutoAdjustEnabled(prev => {
                    const newState = !prev;
                    message = `Auto-regulação ${newState ? 'ativada' : 'desativada'}`;
                    success = true;
                    return newState;
                });
            } else {
                setSystemComponents(prev => {
                    const newState = !prev[systemKey as keyof typeof systemComponents];
                    message = `${component.charAt(0).toUpperCase() + component.slice(1)} ${newState ? 'ativado' : 'desativado'}`;
                    success = true;
                    return { ...prev, [systemKey as keyof typeof systemComponents]: newState };
                });
            }
          } else {
              message = `Ação '${action}' inválida para o componente '${component}'`;
          }
          break;
          
        case 'simulation':
          if (action === 'start') { setIsRunning(true); message = 'Simulação iniciada'; success = true; }
          else if (action === 'stop') { setIsRunning(false); message = 'Simulação pausada'; success = true; }
          else if (action === 'reset') { initializeMesh(); message = 'Simulação reiniciada'; success = true; }
          else { message = `Ação '${action}' inválida para simulação`; }
          break;
          
        case 'material': // Mix ratio control
          if (action === 'set' && value) {
            const ratio = parseFloat(String(value));
            if (!isNaN(ratio)) {
              setMaterialMixRatio(Math.max(0, Math.min(1, ratio)));
              message = `Material (mix ratio) alterado para ${ratio.toFixed(2)}`;
              success = true;
            } else {
                message = `Valor inválido para mix ratio: ${value}`;
            }
          } else {
              message = `Ação '${action}' ou valor inválido para material mix ratio`;
          }
          break;
          
        case 'destination':
          if (action === 'set' && value && destinations[value as DestinationKey]) {
            setSelectedDestination(value as DestinationKey);
            message = `Destino alterado para ${destinations[value as DestinationKey].name}`;
            success = true;
          } else {
              message = `Destino inválido: ${value}`;
          }
          break;
          
        // Conventional controls  
        case 'control':
          if (action === 'set' && value) {
            const [controlName, valueStr] = String(value).split(':');
            const numValue = parseFloat(valueStr);
            if (controlPanels[controlName as keyof typeof controlPanels] && !isNaN(numValue)) {
              const panel = controlPanels[controlName as keyof typeof controlPanels];
              updateControl(controlName, Math.max(panel.min, Math.min(panel.max, numValue)));
              message = `${panel.name} ajustado para ${numValue.toFixed(panel.step < 0.1 ? 2 : (panel.step < 1 ? 1 : 0))}`;
              success = true;
            } else {
                message = `Controle ou valor inválido: ${value}`;
            }
          } else if (action === 'toggle' && value) {
            const controlName = String(value);
            if (controlPanels[controlName as keyof typeof controlPanels]) {
              const panel = controlPanels[controlName as keyof typeof controlPanels];
              updateControl(controlName, !panel.enabled);
              message = `${panel.name} ${!panel.enabled ? 'ativado' : 'desativado'}`;
              success = true;
            } else {
                message = `Controle inválido para toggle: ${value}`;
            }
          } else {
              message = `Ação ou valor inválido para controle: ${value}`;
          }
          break;

        // --- NEW Quantum Commands ---
        case 'propulsionmode':
          if (action === 'set' && (value === 'THERMAL' || value === 'QUANTUM_ELECTRON')) {
            setPropulsionMode(value as PropulsionMode);
            message = `Modo de propulsão definido para ${value}`;
            playQuantumDriveSound(value === 'QUANTUM_ELECTRON');
            success = true;
          } else {
              message = `Modo de propulsão inválido: ${value}`;
          }
          break;

        case 'quantumcontrol':
           if (action === 'set' && value) {
            const [paramName, valueStr] = String(value).split(':');
            const numValue = parseFloat(valueStr);
            if (Object.keys(quantumDriveParams).includes(paramName) && !isNaN(numValue)) {
              updateQuantumControl(paramName as keyof QuantumDriveParams, numValue);
              message = `Parâmetro quântico ${paramName} ajustado para ${numValue.toFixed(2)}`;
              success = true;
            } else {
                message = `Parâmetro quântico ou valor inválido: ${value}`;
            }
          } else {
              message = `Ação ou valor inválido para controle quântico: ${value}`;
          }
          break;
          
        default:
          message = `Componente '${component}' não reconhecido`;
      }
    } catch (error) {
      message = `Erro ao executar comando: ${error instanceof Error ? error.message : String(error)}`;
      console.error("Command Execution Error:", error);
    }
    
    return { success, message };
  }, [controlPanels, initializeMesh, quantumDriveParams, systemComponents, autoAdjustEnabled]); // Added dependencies

  // --- Parse AI Commands ---
  const parseAICommands = (text: string): { response: string; commands: ControlCommand[] } => {
    const commandRegex = /\[COMMAND:([a-zA-Z0-9_:]+)\]/g; 
    const commands: ControlCommand[] = [];
    let response = text;
    
    let match;
    while ((match = commandRegex.exec(text)) !== null) {
      try {
        const commandStr = match[1].trim();
        const parts = commandStr.split(':');
        if (parts.length >= 2) {
            const action = parts[0].toLowerCase();
            const component = parts[1].toLowerCase();
            const value = parts.slice(2).join(':').trim(); 

            commands.push({
              action: action,
              component: component,
              value: value || undefined
            });
            
            response = response.replace(match[0], '');
        } else {
             console.warn('Invalid command format:', match[0]);
        }
      } catch (error) {
        console.error('Error parsing command:', error);
      }
    }
    
    return { response: response.trim(), commands };
  };

  // --- Auto-adjust Temperature Function ---
  const autoAdjustTemperature = useCallback(() => {
    if (!autoAdjustEnabled || !systemComponents.thermalControl || !controlPanels.thermalControlPower.enabled) return;

    const tempDiff = averageInnerTemp - TARGET_INTERNAL_TEMP;
    const absDiff = Math.abs(tempDiff);
    
    if (absDiff > 1) { 
      const adjustmentFactor = 0.05 * controlPanels.thermalControlPower.value;
      const newMixRatio = Math.max(0, Math.min(1, 
        materialMixRatio - (tempDiff * adjustmentFactor * 0.01)
      ));
      
      if (Math.abs(newMixRatio - materialMixRatio) > 0.005) { 
        setMaterialMixRatio(parseFloat(newMixRatio.toFixed(2)));
        playBeep(600, 50);
      }
    }
  }, [averageInnerTemp, autoAdjustEnabled, materialMixRatio, systemComponents.thermalControl, controlPanels.thermalControlPower.value, controlPanels.thermalControlPower.enabled]);

  // --- Status Report Function ---
  const generateStatusReport = useCallback(() => {
    if (!systemComponents.navigation) return;

    const distanceLY = distanceTraveled / METERS_PER_LIGHT_YEAR;
    const velocityFractionC = currentVelocity / SPEED_OF_LIGHT;
    const distRemaining = calculateDistanceRemainingLY();
    
    const statusMessage = `Relatório de Status: Velocidade atual ${velocityFractionC.toFixed(4)}c. ` +
      `Temperatura interna ${averageInnerTemp.toFixed(1)} K. ` +
      `Potência gerada (térmica) ${totalPowerGenerated.toExponential(2)} W. ` +
      `Nível de Energia ${energySourceLevel.toExponential(2)} J. ` +
      (selectedDestination !== 'none' 
        ? `Rumo a ${destinations[selectedDestination].name}, distância restante ${distRemaining === Infinity ? '∞' : distRemaining.toFixed(2)} anos-luz.`
        : `Exploração livre em curso.`);
    
    setChatMessages(prev => [...prev, { 
      sender: 'ai', 
      text: `**Relatório Automático**\n${statusMessage.replace(/\. /g, '.\n')}`
    }]);
    
    speak(statusMessage);
    playStatusSound();
    setLastStatusReport(simulationTime);
  }, [distanceTraveled, currentVelocity, averageInnerTemp, totalPowerGenerated, selectedDestination, simulationTime, systemComponents.navigation, energySourceLevel, calculateDistanceRemainingLY]);

  useEffect(() => { initializeMesh(); }, [initializeMesh]);

  // --- NEW Quantum Physics Calculation (Aligned with PDF Concepts) ---
  const calculateQuantumPhysics = useCallback((params: QuantumDriveParams, velocity: number): QuantumPerformance => {
    if (!systemComponents.quantumDrive) {
        return { quantumThrust: 0, quantumDrag: 0, quantumPowerConsumption: 0, quantumHeatGeneration: 0 };
    }

    const { electronDensityTarget, magneticFieldStrength, magneticFieldAsymmetry, laserIntensity, electronCoherence, crystalIntegrity } = params;

    // Thrust Model: Depends on density, asymmetric field, coherence, integrity (PDF: electron control, asymmetric fields)
    const thrust = K_THRUST * electronDensityTarget * (magneticFieldStrength * magneticFieldAsymmetry) * electronCoherence * crystalIntegrity;

    // Drag Model: Base drag reduced by coherence/integrity (PDF: reduced interaction/drag)
    const dragReduction = electronCoherence * crystalIntegrity * K_DRAG_REDUCTION_FACTOR;
    const effectiveDragCoeff = K_DRAG_BASE * (1 - dragReduction);
    const drag = effectiveDragCoeff * Math.pow(velocity, 2);

    // Power Consumption Model: Base + density + field^2 + laser (PDF: control efforts)
    const powerConsumption = K_POWER_BASE + 
                             K_POWER_DENSITY * electronDensityTarget + 
                             K_POWER_FIELD * Math.pow(magneticFieldStrength, 2) + 
                             K_POWER_LASER * laserIntensity;

    // Heat Generation Model: Based on inefficiency, scaled by control intensity
    const efficiency = QUANTUM_DRIVE_EFFICIENCY_BASE * electronCoherence * crystalIntegrity;
    const inefficiencyFactor = (1 + laserIntensity + magneticFieldAsymmetry) / 2; // Average intensity factor
    const heatGeneration = powerConsumption * (1 - efficiency) * inefficiencyFactor * K_HEAT_FACTOR;

    return {
      quantumThrust: thrust,
      quantumDrag: drag,
      quantumPowerConsumption: powerConsumption,
      quantumHeatGeneration: heatGeneration
    };
  }, [systemComponents.quantumDrive]); // Dependency added

  // --- NEW Quantum State Update (Aligned with PDF Concepts) ---
  const updateQuantumState = useCallback((params: QuantumDriveParams, performance: QuantumPerformance): Partial<QuantumDriveParams> => {
    let { electronCoherence, crystalIntegrity } = params;
    const { quantumThrust, quantumHeatGeneration } = performance;

    // Coherence degrades with laser and field intensity, recovers slowly (PDF: control affects state)
    const coherenceDegradation = (params.laserIntensity * K_COHERENCE_DEGRADE_LASER + 
                                 (params.magneticFieldStrength * params.magneticFieldAsymmetry) * K_COHERENCE_DEGRADE_FIELD) * TIME_STEP;
    electronCoherence -= coherenceDegradation;
    electronCoherence += K_COHERENCE_RECOVERY * (1 - electronCoherence) * TIME_STEP; // Recover towards 1
    electronCoherence = Math.max(0, Math.min(1, electronCoherence));

    // Integrity degrades with thrust stress and heat stress (PDF: material stability)
    crystalIntegrity -= Math.abs(quantumThrust) * K_INTEGRITY_DEGRADE_THRUST * TIME_STEP;
    crystalIntegrity -= quantumHeatGeneration * K_INTEGRITY_DEGRADE_HEAT * TIME_STEP;
    crystalIntegrity = Math.max(0, Math.min(1, crystalIntegrity));

    return { electronCoherence, crystalIntegrity };
  }, []); // Constants are stable, no external dependencies needed


  // --- Simulation Logic --- 
  const runSimulationStep = useCallback(() => {
    if (!systemComponents.propulsion && !systemComponents.powerGeneration && !systemComponents.quantumDrive) return;

    const newSimTime = simulationTime + TIME_STEP;
    setSimulationTime(newSimTime);

    if (Math.floor(newSimTime / 60) > Math.floor(lastStatusReport / 60)) {
      generateStatusReport();
    }

    let calculatedVelocity = currentVelocity;
    let calculatedDistance = distanceTraveled;
    let netForce = 0;
    let currentPowerConsumption = 0;
    let currentHeatGeneration = 0;

    // --- Quantum Drive Physics ---
    let qPerformance: QuantumPerformance = { quantumThrust: 0, quantumDrag: 0, quantumPowerConsumption: 0, quantumHeatGeneration: 0 };
    let qStateUpdate: Partial<QuantumDriveParams> = {};

    if (propulsionMode === 'QUANTUM_ELECTRON' && systemComponents.quantumDrive && energySourceLevel > 0 && quantumDriveParams.crystalIntegrity > 0.01) { // Add integrity check
        qPerformance = calculateQuantumPhysics(quantumDriveParams, calculatedVelocity);
        qStateUpdate = updateQuantumState(quantumDriveParams, qPerformance);
        
        netForce = qPerformance.quantumThrust - qPerformance.quantumDrag;
        currentPowerConsumption += qPerformance.quantumPowerConsumption;
        currentHeatGeneration += qPerformance.quantumHeatGeneration;

        setQuantumDriveParams(prev => ({ ...prev, ...qStateUpdate }));
        setQuantumPerformance(qPerformance);
    } else {
         setQuantumPerformance({ quantumThrust: 0, quantumDrag: 0, quantumPowerConsumption: 0, quantumHeatGeneration: 0 });
         // If drive failed due to integrity, notify
         if (propulsionMode === 'QUANTUM_ELECTRON' && quantumDriveParams.crystalIntegrity <= 0.01 && isRunning) {
             playAlertSound();
             speak("Falha crítica na integridade do cristal quântico. Motor desligado.");
             setChatMessages(prev => [...prev, { sender: 'ai', text: `**ALERTA:** Falha crítica na integridade do cristal quântico. Motor desligado.` }]);
             setPropulsionMode('THERMAL'); // Revert to thermal
         }
    }

    // --- Thermal Drive Physics ---
    if (propulsionMode === 'THERMAL' && systemComponents.propulsion && controlPanels.propulsionPower.enabled) {
        let nextFibIndex = fibonacciIndex;
        let nextFibValue = currentFibValue;
        const isAccelerating = calculatedVelocity < MAX_THERMAL_SPEED;

        if (isAccelerating) {
            const baseIncrease = MAX_THERMAL_SPEED / 10000 * TIME_STEP;
            const velocityIncrease = nextFibValue * baseIncrease * controlPanels.propulsionPower.value;
            calculatedVelocity = Math.min(MAX_THERMAL_SPEED, calculatedVelocity + velocityIncrease);
            
            nextFibIndex++;
            const fibResult = fibGenRef.current.next();
            if (!fibResult.done) {
               nextFibValue = fibResult.value as number;
               setCurrentFibValue(nextFibValue);
               setFibonacciIndex(nextFibIndex);
            } else {
               console.warn("Fibonacci generator exhausted");
            }
        }
        currentPowerConsumption += controlPanels.propulsionPower.value * 5e5; // Example consumption
    }

    // --- Apply Net Force for Acceleration (Quantum Mode Only) ---
    if (propulsionMode === 'QUANTUM_ELECTRON') {
        const acceleration = netForce / SHIP_MASS;
        calculatedVelocity += acceleration * TIME_STEP;
        calculatedVelocity = Math.max(0, Math.min(MAX_QUANTUM_SPEED, calculatedVelocity));
    }
    // Apply passive drag/deceleration if no thrust is active
    else if (netForce === 0 && calculatedVelocity > 0) { 
         // Use the quantum drag model even when coasting, as it represents interaction with the vacuum
         const coastingDrag = K_DRAG_BASE * Math.pow(calculatedVelocity, 2);
         const deceleration = coastingDrag / SHIP_MASS;
         calculatedVelocity = Math.max(0, calculatedVelocity - deceleration * TIME_STEP);
    }

    // --- Update Distance ---
    const avgVelocity = (currentVelocity + calculatedVelocity) / 2;
    calculatedDistance += avgVelocity * TIME_STEP;

    // --- Update Energy Source ---
    const energyConsumed = currentPowerConsumption * TIME_STEP;
    const newEnergyLevel = Math.max(0, energySourceLevel - energyConsumed);
    setEnergySourceLevel(newEnergyLevel);

    if (newEnergyLevel <= 0 && !systemComponents.powerGeneration) {
        if (isRunning) {
            setIsRunning(false);
            playAlertSound();
            speak("Nível de energia crítico. Desligando sistemas.");
            setChatMessages(prev => [...prev, { sender: 'ai', text: `**ALERTA:** Nível de energia crítico. Sistemas desligados.` }]);
        }
    }

    // --- Destination Check ---
    if (selectedDestination !== 'none' && calculatedDistance >= targetDistanceMeters) {
        calculatedDistance = targetDistanceMeters;
        calculatedVelocity = 0;
        if (isRunning) setIsRunning(false);
        playAlertSound();
        speak(`Destino ${destinations[selectedDestination].name} alcançado. Nave parada.`);
        setChatMessages(prev => [...prev, { sender: 'ai', text: `**ALERTA:** Destino ${destinations[selectedDestination].name} alcançado.` }]);
    }

    // --- Update External Temperature ---
    const tempVelocityFactor = propulsionMode === 'QUANTUM_ELECTRON' ? 0.1 : 1.0; 
    const calculatedExternalTemp = COSMIC_BACKGROUND_TEMP + 
        (MAX_EXTERNAL_TEMP - COSMIC_BACKGROUND_TEMP) * 
        Math.pow(Math.min(calculatedVelocity, MAX_THERMAL_SPEED) / MAX_THERMAL_SPEED, 2) * tempVelocityFactor;
    setExternalTemp(calculatedExternalTemp);

    // --- Update Core States ---
    setDistanceTraveled(calculatedDistance);
    setCurrentVelocity(calculatedVelocity);

    // --- Thermal Mesh Update ---
    setMeshState(prevMesh => {
      if (!prevMesh?.[0]) return prevMesh; 
      
      const newMesh = JSON.parse(JSON.stringify(prevMesh));
      let currentTotalPowerGen = 0, innerLayerTempSum = 0, innerLayerCount = 0;
      const matProps = effectiveMaterial;
      
      for (let i = 0; i < TOTAL_ROWS; i++) {
          if (newMesh[i][0].layer === NUM_LAYERS - 1) {
              innerLayerCount += COLS;
          }
      }

      const heatPerInnerPoint = innerLayerCount > 0 ? currentHeatGeneration / innerLayerCount : 0;

      for (let i = 0; i < TOTAL_ROWS; i++) {
        for (let j = 0; j < COLS; j++) {
          const p = newMesh[i][j], T = p.temperature, l = p.layer;
          let dT_intra = 0, dT_inter = 0, dT_ext = 0, dT_quantum = 0;
          
          const T_l = j > 0 ? newMesh[i][j - 1].temperature : T;
          const T_r = j < COLS - 1 ? newMesh[i][j + 1].temperature : T;
          dT_intra = (T_l + T_r - 2 * T);
          
          const T_u = i > 0 ? newMesh[i - 1][j].temperature : T;
          const T_d = i < TOTAL_ROWS - 1 ? newMesh[i + 1][j].temperature : T;
          dT_inter = (T_u + T_d - 2 * T);
          
          if (l === 0 && systemComponents.thermalControl && controlPanels.thermalControlPower.enabled) {
            dT_ext = (calculatedExternalTemp - T) * controlPanels.thermalControlPower.value;
          }

          if (l === NUM_LAYERS - 1 && heatPerInnerPoint > 0) {
              dT_quantum = heatPerInnerPoint * TIME_STEP / (GRID_SIZE * GRID_SIZE); 
          }
          
          const dT = (matProps.k * (dT_intra * HEAT_TRANSFER_COEFFICIENT + dT_inter * INTER_LAYER_HEAT_TRANSFER_COEFFICIENT) + 
                     dT_ext * HEAT_TRANSFER_COEFFICIENT * (l === 0 ? 1 : 0)) * TIME_STEP + dT_quantum;
          p.temperature += dT;
          
          if (systemComponents.powerGeneration && controlPanels.powerGenerationEfficiency.enabled) {
              const dP = Math.max(0, p.temperature - INITIAL_INTERNAL_TEMP);
              const powerGen = Math.pow(matProps.S_eff, 2) * matProps.sigma * dP * 1e-3 * controlPanels.powerGenerationEfficiency.value;
              p.powerGenerated = powerGen; 
              p.efficiencyFactor = matProps.ZT; 
              currentTotalPowerGen += powerGen;
          } else {
              p.powerGenerated = 0;
              p.efficiencyFactor = 0;
          }
          
          if (l === NUM_LAYERS - 1) { 
            innerLayerTempSum += p.temperature; 
          }
        }
      }
      
      setTotalPowerGenerated(currentTotalPowerGen);
      setEnergySourceLevel(prevEnergy => Math.min(INITIAL_ENERGY_LEVEL * 1.1, prevEnergy + currentTotalPowerGen * TIME_STEP));

      if (innerLayerCount > 0) setAverageInnerTemp(innerLayerTempSum / innerLayerCount);
      
      autoAdjustTemperature();
      
      return newMesh;
    });
  }, [
    simulationTime, effectiveMaterial, currentVelocity, distanceTraveled, 
    fibonacciIndex, currentFibValue, selectedDestination, targetDistanceMeters, 
    autoAdjustTemperature, lastStatusReport, generateStatusReport, systemComponents,
    controlPanels.propulsionPower.value, controlPanels.thermalControlPower.value,
    controlPanels.powerGenerationEfficiency.value, controlPanels.propulsionPower.enabled,
    controlPanels.thermalControlPower.enabled, controlPanels.powerGenerationEfficiency.enabled,
    propulsionMode, quantumDriveParams, energySourceLevel, isRunning, 
    calculateQuantumPhysics, updateQuantumState 
  ]);

  // --- Simulation Control --- 
  useEffect(() => {
    if (isRunning && (energySourceLevel > 0 || systemComponents.powerGeneration)) {
      simulationIntervalRef.current = setInterval(runSimulationStep, RENDER_INTERVAL_MS);
    } else {
      if (simulationIntervalRef.current) {
        clearInterval(simulationIntervalRef.current);
        simulationIntervalRef.current = null;
      }
      if (energySourceLevel <= 0 && !systemComponents.powerGeneration && isRunning) {
          setIsRunning(false);
      }
    }
    return () => { 
      if (simulationIntervalRef.current) {
        clearInterval(simulationIntervalRef.current);
        simulationIntervalRef.current = null;
      }
    };
  }, [isRunning, runSimulationStep, systemComponents.powerGeneration, energySourceLevel]); 

  // --- Clean up speech synthesis on unmount ---
  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  // --- Drawing Logic --- 
  useEffect(() => {
    const canvas = canvasRef.current; 
    if (!canvas || !meshState[0]) return; 
    
    const ctx = canvas.getContext('2d'); 
    if (!ctx) return;
    
    const logH = TOTAL_ROWS * GRID_SIZE; 
    if (canvas.height !== logH) canvas.height = logH; 
    if (canvas.width !== MESH_WIDTH) canvas.width = MESH_WIDTH;
    
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    const maxT = Math.max(externalTemp, INITIAL_INTERNAL_TEMP + 100, averageInnerTemp + 50); 
    const minT = Math.min(COSMIC_BACKGROUND_TEMP, INITIAL_INTERNAL_TEMP - 20, averageInnerTemp - 50);
    const tempRange = maxT - minT;
    
    for (let i = 0; i < TOTAL_ROWS; i++) {
      for (let j = 0; j < COLS; j++) { 
        if (!meshState[i]?.[j]) continue; 
        
        const p = meshState[i][j];
        const tR = tempRange > 0 ? Math.max(0, Math.min(1, (p.temperature - minT) / tempRange)) : 0.5;
        const r = Math.round(255 * Math.max(0, tR * 2 - 1));
        const b = Math.round(255 * Math.max(0, 1 - tR * 2));
        const g = 0; 
        
        ctx.fillStyle = `rgb(${r}, ${g}, ${b})`; 
        ctx.fillRect(p.x, p.y, GRID_SIZE, GRID_SIZE); 
      }
    }
    
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.3)'; 
    ctx.lineWidth = 0.5;
    for (let l = 1; l < NUM_LAYERS; l++) { 
      const y = l * ROWS_PER_LAYER * GRID_SIZE; 
      ctx.beginPath(); 
      ctx.moveTo(0, y); 
      ctx.lineTo(MESH_WIDTH, y); 
      ctx.stroke(); 
    }

  }, [meshState, externalTemp, averageInnerTemp]);

  // --- Control Slider Component ---
  const ControlSlider: React.FC<{
    control: { name: string; value: number; min: number; max: number; step: number; unit: string; enabled?: boolean };
    controlName: string;
    icon: React.ReactNode;
    colorClass: string; 
    onChange: (value: number) => void;
    enabled?: boolean;
  }> = ({ control, controlName, icon, colorClass, onChange, enabled = true }) => (
    <div className="mb-2 p-2 bg-gray-700 rounded border border-gray-600">
      <div className="flex justify-between items-center mb-1">
        <label htmlFor={controlName} className="flex items-center text-xs font-medium text-gray-300">
          {React.cloneElement(icon as React.ReactElement, { size: 14, className: "mr-1" })}
          <span>{control.name}</span>
        </label>
      </div>
      <div className="flex items-center">
        <input
          id={controlName}
          type="range"
          min={control.min}
          max={control.max}
          step={control.step}
          value={control.value}
          onChange={(e) => onChange(parseFloat(e.target.value))}
          className={`flex-grow h-1.5 rounded-lg appearance-none cursor-pointer ${colorClass} bg-gray-500 disabled:opacity-50 disabled:cursor-not-allowed`}
          disabled={!enabled}
          style={{ background: `linear-gradient(to right, var(--slider-color, #ccc) ${((control.value - control.min) / (control.max - control.min)) * 100}%, #4b5563 ${((control.value - control.min) / (control.max - control.min)) * 100}%)` }}
        />
        <span className="ml-2 text-xs font-mono w-12 text-right">
          {control.value.toFixed(control.step < 0.1 ? 2 : (control.step < 1 ? 1 : 0))}{control.unit}
        </span>
      </div>
    </div>
  );

  // --- System Status Indicator Component ---
  const SystemStatusIndicator: React.FC<{
    label: string;
    isActive: boolean;
    icon: React.ReactNode;
    onToggle?: () => void; 
    tooltip?: string;
  }> = ({ label, isActive, icon, onToggle, tooltip }) => {
    const content = (
        <>
            {React.cloneElement(icon as React.ReactElement, { size: 12 })}
            <span>{label}</span>
        </>
    );
    const className = `flex items-center space-x-1 p-1 rounded border text-xs ${isActive ? 'bg-green-700 border-green-600 text-white' : 'bg-gray-600 border-gray-500 text-gray-300'} ${onToggle ? 'hover:bg-gray-500 cursor-pointer' : ''}`;

    return onToggle ? (
        <button onClick={onToggle} className={className} title={tooltip}>
            {content}
        </button>
    ) : (
        <div className={className} title={tooltip}>
            {content}
        </div>
    );
  };

  // --- Event Handlers --- 
  const handleMixRatioChange = (e: React.ChangeEvent<HTMLInputElement>) => setMaterialMixRatio(Number(e.target.value));
  const handleDestinationChange = (destKey: DestinationKey) => {
      setSelectedDestination(destKey);
      playBeep(700, 80);
  }
  
  const toggleSimulation = () => {
    if (!isRunning && energySourceLevel <= 0 && !systemComponents.powerGeneration) {
        playAlertSound();
        speak("Impossível iniciar simulação. Nível de energia crítico.");
        return;
    }
    setIsRunning(!isRunning);
    playBeep(isRunning ? 700 : 900, 100);
  };
  
  const resetSimulation = () => { 
    if (isRunning) setIsRunning(false);
    initializeMesh();
    playBeep(600, 200);
  };
  
  const toggleAutoAdjust = () => {
    setAutoAdjustEnabled(!autoAdjustEnabled);
    playBeep(autoAdjustEnabled ? 500 : 700, 100);
  };

  const toggleComponent = (component: keyof typeof systemComponents) => {
    setSystemComponents(prev => {
        const newState = !prev[component];
        playBeep(prev[component] ? 500 : 700, 100);
        return { ...prev, [component]: newState };
    });
  };

  const togglePropulsionMode = () => {
      const newMode = propulsionMode === 'THERMAL' ? 'QUANTUM_ELECTRON' : 'THERMAL';
      setPropulsionMode(newMode);
      playQuantumDriveSound(newMode === 'QUANTUM_ELECTRON');
  };

  // --- AI Chat Logic --- 
  const handleChatSend = useCallback(async () => {
    if (!chatInput.trim() || isAiThinking) return;
    
    playBeep(1200, 50);
    const userMsg: ChatMessage = { sender: 'user', text: chatInput }; 
    setChatMessages(prev => [...prev, userMsg]); 
    setChatInput(''); 
    setIsAiThinking(true);
    
    const distanceLY = distanceTraveled / METERS_PER_LIGHT_YEAR;
    const velocityFractionC = currentVelocity / SPEED_OF_LIGHT;
    const targetInfo = selectedDestination === 'none' ? 'Exploração livre.' : `Destino: ${destinations[selectedDestination].name} (${destinations[selectedDestination].distanceLY.toFixed(2)} anos-luz).`;
    
    const componentsStatus = Object.entries(systemComponents)
      .map(([key, value]) => `${key}: ${value ? 'ON' : 'OFF'}`)
      .join(', ');
    
    const thermalControlsStatus = Object.entries(controlPanels)
      .map(([key, panel]) => `${panel.name}: ${panel.enabled ? 'ON' : 'OFF'} (${(panel.value * 100).toFixed(0)}%)`)
      .join(', ');

    const quantumParamsStatus = `Densidade Elétrons Alvo: ${quantumDriveParams.electronDensityTarget.toFixed(2)}, Campo Magnético: ${quantumDriveParams.magneticFieldStrength.toFixed(1)}T, Assimetria Campo: ${quantumDriveParams.magneticFieldAsymmetry.toFixed(2)}, Intensidade Laser: ${quantumDriveParams.laserIntensity.toFixed(2)}, Coerência: ${(quantumDriveParams.electronCoherence * 100).toFixed(0)}%, Integridade Cristal: ${(quantumDriveParams.crystalIntegrity * 100).toFixed(0)}%`;
    const quantumPerfStatus = `Impulso Quântico: ${quantumPerformance.quantumThrust.toExponential(2)}N, Arrasto Quântico: ${quantumPerformance.quantumDrag.toExponential(2)}N, Consumo Quântico: ${quantumPerformance.quantumPowerConsumption.toExponential(2)}W`;

    const context = `Contexto: IA assistente numa simulação de Malha Antitérmica e Motor Quântico para uma espaçonave interestelar. 
      Massa da Nave: ${SHIP_MASS} kg.
      Tempo: ${formatTime(simulationTime)} (${(simulationTime / SECONDS_PER_YEAR).toFixed(2)} anos). 
      Distância: ${distanceLY.toExponential(3)} anos-luz. 
      Velocidade: ${velocityFractionC.toFixed(4)}c (${(currentVelocity / 1000).toFixed(0)} km/s). 
      ${targetInfo} 
      ${NUM_LAYERS} camadas de ${effectiveMaterial.name} expostas a ${externalTemp.toFixed(1)}K. 
      Objetivo Térmico: Manter temp. interna próxima de ${TARGET_INTERNAL_TEMP.toFixed(1)}K. Temp. interna atual: ${averageInnerTemp.toFixed(1)}K. 
      Potência Gerada (Térmica): ${totalPowerGenerated.toExponential(2)}W. 
      Nível de Energia Principal: ${energySourceLevel.toExponential(2)} J.
      Modo de Propulsão Atual: ${propulsionMode}.
      Status dos Componentes: ${componentsStatus}.
      Status Controles Térmicos: ${thermalControlsStatus}.
      Status Parâmetros Quânticos: ${quantumParamsStatus}.
      Status Performance Quântica: ${quantumPerfStatus}.
      Auto-Ajuste Térmico: ${autoAdjustEnabled ? 'ON' : 'OFF'}.
      
      Comandos disponíveis [COMMAND:action:component:value]: 
      - Sistemas (toggle): propulsion, thermalControl, powerGeneration, navigation, lifeSupport, quantumDrive, autoadjust
      - Simulação (start, stop, reset): simulation
      - Materiais (set): material (valor: mix_ratio 0-1)
      - Destino (set): destination (nome da chave: ex, proxima_centauri)
      - Controles Térmicos (set/toggle): control (formato set: nome:valor, ex: propulsionPower:0.8; formato toggle: nome, ex: propulsionPower)
      - Modo Propulsão (set): propulsionMode (valor: THERMAL ou QUANTUM_ELECTRON)
      - Controles Quânticos (set): quantumControl (formato: nomeParametro:valor, ex: electronDensityTarget:0.7)
      - Consultas (sem ação/valor): query (componente: quantumStatus, energyLevel, fullStatus)
      
      Responda de forma concisa e técnica. Inclua comandos entre colchetes quando necessário.`;
    
    try {
      const response = await fetch(`${API_URL}?key=${API_KEY}`, { 
        method: 'POST', 
        headers: { 'Content-Type': 'application/json' }, 
        body: JSON.stringify({ 
          contents: [{ 
            parts: [{ 
              text: context + "\n\nHistórico recente:\n" + 
                    chatMessages.slice(-4).map(m => `${m.sender === 'user' ? 'Humano' : 'IA'}: ${m.text}`).join('\n') + 
                    "\n\nHumano: " + userMsg.text
            }] 
          }] 
        }) 
      });
      
      if (!response.ok) { 
        const err = await response.json(); 
        throw new Error(err?.error?.message || `API fail: ${response.status}`); 
      }
      
      const data = await response.json(); 
      let aiText = 'Não consegui processar a resposta da IA.';
      
      if (data.candidates?.[0]?.content?.parts?.[0]?.text) {
        aiText = data.candidates[0].content.parts[0].text;
      }

      const { response: parsedResponse, commands } = parseAICommands(aiText);

      let queryResponses: string[] = [];
      const nonQueryCommands: ControlCommand[] = [];

      commands.forEach(cmd => {
          if (cmd.action === 'query') {
              let queryResult = '';
              switch (cmd.component) {
                  case 'quantumstatus':
                      queryResult = `Status Quântico: ${quantumParamsStatus}. ${quantumPerfStatus}.`;
                      break;
                  case 'energylevel':
                      queryResult = `Nível de Energia: ${energySourceLevel.toExponential(2)} J.`;
                      break;
                  case 'fullstatus': 
                       queryResult = `Status Completo: ${context}`; 
                       break;
                  default:
                      queryResult = `Consulta '${cmd.component}' não reconhecida.`;
              }
              queryResponses.push(queryResult);
          } else {
              nonQueryCommands.push(cmd);
          }
      });

      const finalAiResponse = queryResponses.length > 0 
          ? `${parsedResponse}\n\n${queryResponses.join('\n')}`
          : parsedResponse;

      setChatMessages(prev => [...prev, { sender: 'ai', text: finalAiResponse }]);
      speak(finalAiResponse);

      nonQueryCommands.forEach((cmd, index) => {
        setTimeout(() => {
          const result = executeControlCommand(cmd);
          if (result.message) {
            if (!result.success) {
                setChatMessages(prev => [...prev, { sender: 'ai', text: `*Falha Comando:* ${result.message}` }]);
                playAlertSound();
            } else {
                 console.log(`Command executed: ${result.message}`);
                 playBeep(1000, 30); 
            }
          }
        }, (index + 1) * 250); 
      });

    } catch (error) {
      console.error("Chat API Error:", error);
      const errorMsg = `Erro de comunicação com IA: ${error instanceof Error ? error.message : String(error)}`;
      setChatMessages(prev => [...prev, { sender: 'ai', text: errorMsg }]);
      speak(errorMsg);
      playAlertSound();
    } finally {
      setIsAiThinking(false);
    }
  }, [chatInput, isAiThinking, distanceTraveled, currentVelocity, selectedDestination, systemComponents, controlPanels, quantumDriveParams, quantumPerformance, simulationTime, effectiveMaterial, externalTemp, averageInnerTemp, totalPowerGenerated, energySourceLevel, propulsionMode, autoAdjustEnabled, chatMessages, executeControlCommand]);

  // Scroll chat to bottom
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  // --- JSX Structure --- 
  const distanceRemainingLY = calculateDistanceRemainingLY();

  return (
    <div className="bg-gray-900 text-gray-200 min-h-screen p-4 font-sans flex flex-col">
      {/* --- Top Row: Status Panels --- */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-3">
        {/* Panel 1: General Status */}
        <div className="bg-gray-800 p-3 rounded border border-red-600/50 shadow-md">
          <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Clock size={14} className="mr-1"/> Status Geral</h3>
          <div className="text-xs space-y-1">
            <p>Tempo: <span className="font-mono text-cyan-400 float-right">{formatTime(simulationTime)}</span></p>
            <p>Distância: <span className="font-mono text-cyan-400 float-right">{(distanceTraveled / METERS_PER_LIGHT_YEAR).toExponential(2)} LY</span></p>
            <p>Velocidade: <span className="font-mono text-cyan-400 float-right">{(currentVelocity / SPEED_OF_LIGHT).toFixed(4)} c</span></p>
            <p>Potência Térmica: <span className="font-mono text-cyan-400 float-right">{totalPowerGenerated.toExponential(2)} W</span></p>
            <p>Energia Principal: <span className="font-mono text-yellow-400 float-right">{energySourceLevel.toExponential(2)} J</span></p>
          </div>
        </div>

        {/* Panel 2: Thermal & Material Status */}
        <div className="bg-gray-800 p-3 rounded border border-red-600/50 shadow-md">
          <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Thermometer size={14} className="mr-1"/> Status Térmico</h3>
          <div className="text-xs space-y-1 mb-2">
            <p>Temp. Externa: <span className="font-mono text-yellow-400 float-right">{externalTemp.toFixed(1)} K</span></p>
            <p>Temp. Interna: <span className="font-mono text-yellow-400 float-right">{averageInnerTemp.toFixed(1)} K</span></p>
            <p>Alvo Interno: <span className="font-mono text-gray-400 float-right">{TARGET_INTERNAL_TEMP.toFixed(1)} K</span></p>
          </div>
          <h4 className="text-xs font-semibold mt-2 mb-1 text-red-400 flex items-center"><Blend size={12} className="mr-1"/> Material (Malha Térmica)</h4>
          <div className="text-xs space-y-1">
             <p className="truncate" title={effectiveMaterial.name}>Mat. Efetivo: <span className="font-mono text-purple-400 float-right">{effectiveMaterial.ZT.toFixed(2)} ZT</span></p>
             <div className="flex items-center justify-between">
                <label htmlFor="mixRatio" className="text-xs">Mix Ratio:</label>
                <input 
                    id="mixRatio"
                    type="range" 
                    min="0" max="1" step="0.01" 
                    value={materialMixRatio} 
                    onChange={handleMixRatioChange} 
                    className="w-1/2 h-1.5 rounded-lg appearance-none cursor-pointer accent-purple-500 bg-gray-600 mx-1"
                />
                <span className="font-mono text-purple-400 w-8 text-right">{(materialMixRatio * 100).toFixed(0)}%</span>
             </div>
             <div className="flex items-center justify-between mt-1">
                <span className="text-xs">Auto-Ajuste Térmico:</span>
                <button 
                    onClick={toggleAutoAdjust}
                    className={`px-1.5 py-0.5 rounded text-xs font-semibold ${autoAdjustEnabled ? 'bg-green-600 hover:bg-green-700 border-green-700' : 'bg-red-600 hover:bg-red-700 border-red-700'} border`}
                >
                    {autoAdjustEnabled ? 'ON' : 'OFF'}
                </button>
             </div>
          </div>
        </div>

        {/* Panel 3: System Status */}
        <div className="bg-gray-800 p-3 rounded border border-red-600/50 shadow-md">
          <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Settings size={14} className="mr-1"/> Status Sistemas</h3>
          <div className="grid grid-cols-2 gap-1.5">
            <SystemStatusIndicator label="Prop. Térmica" isActive={systemComponents.propulsion && controlPanels.propulsionPower.enabled} icon={<Rocket/>} onToggle={() => toggleComponent('propulsion')} tooltip="Propulsão Térmica Convencional"/>
            <SystemStatusIndicator label="Motor Quântico" isActive={systemComponents.quantumDrive} icon={<Waves/>} onToggle={() => toggleComponent('quantumDrive')} tooltip="Motor de Propulsão Quântica"/>
            <SystemStatusIndicator label="Controle Térmico" isActive={systemComponents.thermalControl && controlPanels.thermalControlPower.enabled} icon={<Wind/>} onToggle={() => toggleComponent('thermalControl')} />
            <SystemStatusIndicator label="Geração Energia" isActive={systemComponents.powerGeneration && controlPanels.powerGenerationEfficiency.enabled} icon={<Zap/>} onToggle={() => toggleComponent('powerGeneration')} tooltip="Geração de Energia (Seebeck)"/>
            <SystemStatusIndicator label="Navegação" isActive={systemComponents.navigation} icon={<MapPin/>} onToggle={() => toggleComponent('navigation')} />
            <SystemStatusIndicator label="Suporte Vital" isActive={systemComponents.lifeSupport && controlPanels.lifeSupportPower.enabled} icon={<HeartPulse/>} onToggle={() => toggleComponent('lifeSupport')} />
          </div>
           <h4 className="text-xs font-semibold mt-3 mb-1 text-red-400">Modo de Propulsão</h4>
           <button 
                onClick={togglePropulsionMode}
                className={`w-full px-2 py-1 rounded border text-sm font-semibold flex items-center justify-center transition-colors duration-150 ${propulsionMode === 'QUANTUM_ELECTRON' ? 'bg-purple-600 hover:bg-purple-700 border-purple-700' : 'bg-orange-600 hover:bg-orange-700 border-orange-700'} text-white`}
            >
                {propulsionMode === 'QUANTUM_ELECTRON' ? <Waves size={16} className="mr-1"/> : <Rocket size={16} className="mr-1"/>}
                {propulsionMode === 'QUANTUM_ELECTRON' ? 'QUÂNTICO' : 'TÉRMICO'}
            </button>
        </div>

        {/* Panel 4: Navigation */}
        <div className="bg-gray-800 p-3 rounded border border-red-600/50 shadow-md">
          <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Target size={14} className="mr-1"/> Navegação</h3>
          <div className="text-xs space-y-1 mb-2">
            <p>Destino: <span className="font-mono text-green-400 float-right truncate" title={destinations[selectedDestination].name}>{destinations[selectedDestination].name}</span></p>
            <p>Dist. Total: <span className="font-mono text-green-400 float-right">{destinations[selectedDestination].distanceLY === Infinity ? '∞' : destinations[selectedDestination].distanceLY.toFixed(2)} LY</span></p>
            <p>Dist. Restante: <span className="font-mono text-green-400 float-right">{distanceRemainingLY === Infinity ? '∞' : distanceRemainingLY.toFixed(2)} LY</span></p>
          </div>
           <div className="relative pt-1">
              <div className="overflow-hidden h-1.5 mb-2 text-xs flex rounded bg-gray-600">
                <div style={{ width: `${selectedDestination === 'none' || destinations[selectedDestination].distanceLY === Infinity ? 0 : Math.min(100, (1 - distanceRemainingLY / destinations[selectedDestination].distanceLY) * 100)}%` }}
                     className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-green-500 transition-all duration-300">
                </div>
              </div>
            </div>
          <h4 className="text-xs font-semibold mt-2 mb-1 text-red-400">Selecionar Destino</h4>
          <select 
            value={selectedDestination}
            onChange={(e) => handleDestinationChange(e.target.value as DestinationKey)}
            className="w-full p-1 text-xs bg-gray-700 border border-gray-600 rounded text-gray-200 focus:outline-none focus:border-red-500"
            disabled={!systemComponents.navigation}
          >
            {Object.entries(destinations).map(([key, dest]) => (
              <option key={key} value={key}>{dest.name}</option>
            ))}
          </select>
        </div>
      </div>

      {/* --- Bottom Row: Visualization and Controls --- */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-3 flex-grow min-h-0">
        {/* Left Panel: Visualization & Sim Controls */}
        <div className="lg:col-span-2 bg-gray-800 p-3 rounded border border-red-600/50 shadow-md flex flex-col items-center">
          <h3 className="text-sm font-semibold mb-2 text-red-400 self-start border-b border-red-600/30 pb-1 w-full flex items-center"><Layers size={14} className="mr-1"/> Visualização da Malha Térmica</h3>
          <div className="bg-black border border-gray-700 rounded overflow-hidden mb-2" style={{ width: MESH_WIDTH, height: MESH_HEIGHT }}>
             <canvas ref={canvasRef} width={MESH_WIDTH} height={MESH_HEIGHT} />
          </div>
          <div className="flex space-x-2">
            <button 
              onClick={toggleSimulation}
              className={`px-3 py-1 rounded border text-sm font-semibold flex items-center transition-colors duration-150 ${isRunning ? 'bg-yellow-600 hover:bg-yellow-700 border-yellow-700' : 'bg-green-600 hover:bg-green-700 border-green-700'} text-white disabled:opacity-50 disabled:cursor-not-allowed`}
              disabled={energySourceLevel <= 0 && !systemComponents.powerGeneration}
            >
              {isRunning ? <Pause size={16} className="mr-1"/> : <Play size={16} className="mr-1"/>}
              {isRunning ? 'Pausar' : 'Iniciar'}
            </button>
            <button 
              onClick={resetSimulation}
              className="px-3 py-1 rounded border border-red-600/80 text-sm font-semibold flex items-center bg-gray-700 hover:bg-red-700 hover:text-white text-red-400 transition-colors duration-150"
            >
              <RotateCcw size={16} className="mr-1"/> Resetar
            </button>
          </div>
        </div>

        {/* Right Panel: Detailed Controls & AI Chat */}
        <div className="lg:col-span-1 bg-gray-800 p-3 rounded border border-red-600/50 shadow-md flex flex-col space-y-3 overflow-hidden">
          {/* Tabbed Controls */} 
          <div className="flex-grow flex flex-col min-h-0">
              {/* Sub-Panel 1: Thermal Controls */}
              <div className="bg-gray-850 p-2 rounded border border-gray-700 mb-3">
                <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><SlidersHorizontal size={14} className="mr-1"/> Controles Térmicos/Convencionais</h3>
                <ControlSlider 
                    control={controlPanels.propulsionPower} 
                    controlName="propulsionPower" 
                    icon={<Rocket/>} 
                    colorClass="accent-orange-500" 
                    onChange={(v) => updateControl("propulsionPower", v)} 
                    enabled={controlPanels.propulsionPower.enabled && propulsionMode === 'THERMAL'} 
                />
                <ControlSlider 
                    control={controlPanels.thermalControlPower} 
                    controlName="thermalControlPower" 
                    icon={<Wind/>} 
                    colorClass="accent-blue-500" 
                    onChange={(v) => updateControl("thermalControlPower", v)} 
                    enabled={controlPanels.thermalControlPower.enabled} 
                />
                <ControlSlider 
                    control={controlPanels.powerGenerationEfficiency} 
                    controlName="powerGenerationEfficiency" 
                    icon={<Zap/>} 
                    colorClass="accent-yellow-500" 
                    onChange={(v) => updateControl("powerGenerationEfficiency", v)} 
                    enabled={controlPanels.powerGenerationEfficiency.enabled} 
                />
                <ControlSlider 
                    control={controlPanels.lifeSupportPower} 
                    controlName="lifeSupportPower" 
                    icon={<HeartPulse/>} 
                    colorClass="accent-green-500" 
                    onChange={(v) => updateControl("lifeSupportPower", v)} 
                    enabled={controlPanels.lifeSupportPower.enabled} 
                />
              </div>

              {/* Sub-Panel 2: Quantum Controls */}
              <div className="bg-gray-850 p-2 rounded border border-gray-700 mb-3">
                <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Waves size={14} className="mr-1"/> Controles Quânticos</h3>
                 <ControlSlider 
                    control={{ name: "Densidade Elétrons", value: quantumDriveParams.electronDensityTarget, min: 0, max: 1, step: 0.01, unit: "%"}} 
                    controlName="electronDensityTarget" 
                    icon={<Sigma/>} 
                    colorClass="accent-cyan-500" 
                    onChange={(v) => updateQuantumControl("electronDensityTarget", v)} 
                    enabled={propulsionMode === 'QUANTUM_ELECTRON' && systemComponents.quantumDrive}
                />
                 <ControlSlider 
                    control={{ name: "Campo Magnético", value: quantumDriveParams.magneticFieldStrength, min: 0, max: 10, step: 0.1, unit: "T"}} 
                    controlName="magneticFieldStrength" 
                    icon={<Magnet/>} 
                    colorClass="accent-purple-500" 
                    onChange={(v) => updateQuantumControl("magneticFieldStrength", v)} 
                    enabled={propulsionMode === 'QUANTUM_ELECTRON' && systemComponents.quantumDrive}
                />
                 <ControlSlider 
                    control={{ name: "Assimetria Campo", value: quantumDriveParams.magneticFieldAsymmetry, min: 0, max: 1, step: 0.01, unit: "%"}} 
                    controlName="magneticFieldAsymmetry" 
                    icon={<Binary/>} 
                    colorClass="accent-pink-500" 
                    onChange={(v) => updateQuantumControl("magneticFieldAsymmetry", v)} 
                    enabled={propulsionMode === 'QUANTUM_ELECTRON' && systemComponents.quantumDrive}
                />
                 <ControlSlider 
                    control={{ name: "Intensidade Laser", value: quantumDriveParams.laserIntensity, min: 0, max: 1, step: 0.01, unit: "%"}} 
                    controlName="laserIntensity" 
                    icon={<Crosshair/>} 
                    colorClass="accent-red-500" 
                    onChange={(v) => updateQuantumControl("laserIntensity", v)} 
                    enabled={propulsionMode === 'QUANTUM_ELECTRON' && systemComponents.quantumDrive}
                />
                {/* Readouts for Quantum Performance */} 
                <div className="mt-2 text-xs space-y-0.5 border-t border-gray-700 pt-2">
                    <p>Impulso: <span className="font-mono text-cyan-400 float-right">{quantumPerformance.quantumThrust.toExponential(1)} N</span></p>
                    <p>Arrasto: <span className="font-mono text-red-400 float-right">{quantumPerformance.quantumDrag.toExponential(1)} N</span></p>
                    <p>Consumo: <span className="font-mono text-yellow-400 float-right">{quantumPerformance.quantumPowerConsumption.toExponential(1)} W</span></p>
                    <p>Coerência: <span className="font-mono text-purple-400 float-right">{(quantumDriveParams.electronCoherence * 100).toFixed(0)}%</span></p>
                    <p>Integridade: <span className="font-mono text-green-400 float-right">{(quantumDriveParams.crystalIntegrity * 100).toFixed(0)}%</span></p>
                </div>
              </div>

              {/* Sub-Panel 3: AI Chat */}
              <div className="bg-gray-850 p-2 rounded border border-gray-700 flex flex-col flex-grow min-h-0">
                <h3 className="text-sm font-semibold mb-2 text-red-400 border-b border-red-600/30 pb-1 flex items-center"><Bot size={14} className="mr-1"/> Assistente IA</h3>
                <div className="flex-grow overflow-y-auto mb-2 pr-1 text-xs space-y-2 scrollbar-thin scrollbar-thumb-gray-600 scrollbar-track-gray-800">
                  {chatMessages.map((msg, index) => (
                    <div key={index} className={`p-1.5 rounded ${msg.sender === 'user' ? 'bg-gray-700 ml-4' : 'bg-gray-600 mr-4'}`}>
                      <p style={{ whiteSpace: 'pre-wrap' }} dangerouslySetInnerHTML={{ __html: msg.text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br />') }} />
                    </div>
                  ))}
                  {isAiThinking && <p className="text-center text-gray-400 italic">IA pensando...</p>}
                  <div ref={chatEndRef} />
                </div>
                <div className="flex items-center mt-auto border-t border-gray-700 pt-2">
                  <input 
                    type="text" 
                    value={chatInput} 
                    onChange={(e) => setChatInput(e.target.value)} 
                    onKeyPress={(e) => e.key === 'Enter' && handleChatSend()}
                    placeholder="Comando para IA..." 
                    className="flex-grow p-1 text-xs bg-gray-700 border border-gray-600 rounded-l focus:outline-none focus:border-red-500 text-gray-200"
                    disabled={isAiThinking}
                  />
                  <button 
                    onClick={handleChatSend} 
                    disabled={isAiThinking || !chatInput.trim()}
                    className="p-1 bg-red-600 hover:bg-red-700 text-white rounded-r border border-red-600 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <Send size={16}/>
                  </button>
                </div>
              </div>
          </div>
        </div>
      </div>

    </div>
  );
};

export default ThermalMeshPage;

